// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26blUxztettoxshVTkopupptvoe9_vlU',
    appId: '1:5143857423:web:fd5e3112047bade394167a',
    messagingSenderId: '5143857423',
    projectId: 'news-b8d1c',
    authDomain: 'news-b8d1c.firebaseapp.com',
    storageBucket: 'news-b8d1c.firebasestorage.app',
    measurementId: 'G-PMM1606LPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaN-8mUEsWTM_e_Bbl-NCEvyKx7JlB1g',
    appId: '1:5143857423:android:3ffe4ef912f964a494167a',
    messagingSenderId: '5143857423',
    projectId: 'news-b8d1c',
    storageBucket: 'news-b8d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURXtQMneo4_JQLiIoKnTpxoE5ezJVcXY',
    appId: '1:5143857423:ios:071beb80305c475e94167a',
    messagingSenderId: '5143857423',
    projectId: 'news-b8d1c',
    storageBucket: 'news-b8d1c.firebasestorage.app',
    iosBundleId: 'com.syncnews.news',
  );
}
